### ISSUE TITLE
how i can use this for multiple images  and slide images after open image fullscreen

### ISSUE THREAD

**Issue by mahmoud310** [SimonGolms/ngx-ionic-image-viewer#11]
i'm trying use this plugin with ion-slide

`
<ion-slide *ngFor="let b of product.images">
            <ion-img-viewer scheme="dark" [src]="b.src"></ion-img-viewer>
</ion-slide>
`

**Comment by SimonGolms** [comment]
Hi @mahmoud310, unfortunately this 'gallery' feature is not supported yet. You may interested in this video: [How to Create an Ionic 4 Image Gallery with Zoom](https://youtu.be/yHDnVarTr2E)

**Comment by mahmoud310** [comment]
hi @SimonGolms thx a lot 
but this video show slider with open one image , i need slider work when open image fullscreen.

**Comment by SimonGolms** [comment]
Unfortunately, I don't exactly understand your question... since it works inside a slider. See: https://stackblitz.com/edit/github-vrgem1
```
<ion-slides pager>
  <ion-slide *ngFor="let image of images">
    <ion-img-viewer scheme="dark" [src]="image"></ion-img-viewer>
  </ion-slide>
</ion-slides>
```

**Comment by SimonGolms** [comment]
Hi @mahmoud310, any news? Otherwise I will close this issue in 7 days.

**Comment by jaydeep9rl** [comment]
@SimonGolms  I am looking for the same kind of behavior.
I used this plugin on ion-image (as directive) inside ion-slide, and when I tap on the image, it opens up the full-screen image but only one. What we are looking for is to slide through multiple images when it is in the full-screen mode.

**Comment by SimonGolms** [comment]
Hi @jaydeep9rl, thanks for you description and I think this was also the meaning from @mahmoud310?
Unfortunately, this was currently not the main goal I wanted to achieve with this component... but I create an extra feature request. Feel free to contribute and is very welcome, since it will not be my highest priority to implement this feature right now.

In the meantime take a look to the [gallery](https://fivethree-team.github.io/ionic-4-components/gallery) component from [fivethree](https://github.com/fivethree-team).

**Comment by jaydeep9rl** [comment]
Yes, we both meant the same thing.

Sure! and Thank you for sharing the links!

**Comment by SimonGolms** [comment]
The feature request #21 is created and closes this issue.
