### ISSUE TITLE
Image in zoom container is draggable, it should not be as its reacting for pinch and custom drag 

### ISSUE THREAD

**Issue by Prabaharancs** [SimonGolms/ngx-ionic-image-viewer#3]
Please have a look at the below screenshot and **prevent the default drag**

![screenshot](https://user-images.githubusercontent.com/362136/69841337-bc7fa680-1299-11ea-9362-d3981d845b7e.png)

**Comment by SimonGolms** [comment]
Hi @Prabaharancs , this topic has kept me busy for a long time, because draggable only works in desktop mode and when you drag the image vertical, but not on mobile devices at all - which is completely acceptable from my point of view.

Anyway, with PR #5 and the release of version `0.1.0` the props `slideOptions` were added and allows you to  directly access the api of the swiper instance . In your case, the following configuration should disable the draggable functionality on desktop too.
```html
<ion-img-viewer src="./demo.jpg" [slideOptions]="{touchAngle: 90}"></ion-img-viewer>
```

**Comment by Prabaharancs** [comment]
Thanks for the fix, let me test it out.
